#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Runs every Windows-only verification Frost's checklist is waiting on, in
    order, and writes one transcript.

.DESCRIPTION
    Phases 9 and 10 and part of Phase 7 cannot be completed on a non-Windows
    host: they ask for measured numbers, an MSIX build, and an on-screen
    observation. This script runs the measurable part unattended and records
    exactly what happened, so the results can be read — or handed back to the
    build loop — without anyone transcribing console output by hand.

    Nothing here is destructive. It builds, it captures a few short recordings
    into a temporary folder, and it reads performance counters. The two things
    it cannot do are the two that need a human: playing a game while it measures
    (step 8) and looking at the screen (step 9).

.PARAMETER Seconds
    Length of each capture test. 30 is enough for a verdict; 60 gives a steadier
    CPU average.

.PARAMETER OutputPath
    Where the transcript goes. Defaults to ./artifacts/windows-verification.md.

.PARAMETER SkipSoak
    Skip the 10-minute memory soak, which is by far the longest step.

.EXAMPLE
    ./verify-windows.ps1
    ./verify-windows.ps1 -Seconds 60 -SkipSoak
#>
[CmdletBinding()]
param(
    [int]$Seconds = 30,
    [string]$OutputPath = (Join-Path $PSScriptRoot 'artifacts/windows-verification.md'),
    [switch]$SkipSoak
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'   # a failing step is a result, not a crash

$repoRoot = $PSScriptRoot
$scratch = Join-Path ([System.IO.Path]::GetTempPath()) "frost-verify-$(Get-Random)"
New-Item -ItemType Directory -Force -Path $scratch | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

$report = [System.Collections.Generic.List[string]]::new()
$results = [System.Collections.Generic.List[object]]::new()

function Add-Line([string]$text) { $report.Add($text) }

function Invoke-Step {
    param(
        [string]$Name,
        [string]$Why,
        [scriptblock]$Body,
        [hashtable]$ExitMeanings = @{}
    )

    Write-Host "==> $Name" -ForegroundColor Cyan

    $global:LASTEXITCODE = 0
    $output = & $Body 2>&1 | Out-String

    # Read through Get-Variable: StrictMode turns a bare $LASTEXITCODE into an
    # error when no external command has run yet in this session.
    $code = (Get-Variable -Name LASTEXITCODE -Scope Global -ValueOnly -ErrorAction SilentlyContinue)
    if ($null -eq $code) { $code = 0 }

    $verdict = if ($code -eq 0) { 'PASS' } else { 'FAIL' }
    $meaning = if ($ExitMeanings.ContainsKey($code)) { $ExitMeanings[$code] } else { $null }

    # The Shell step is informational: it is expected to fail until Phase 7's
    # XAML exists, so it is reported but never counted as a failure.
    $isExpectedFailure = $Name -like '*expected to fail*'
    if ($isExpectedFailure -and $code -ne 0) { $verdict = 'EXPECTED' }

    $results.Add([pscustomobject]@{ Name = $Name; Code = $code; Verdict = $verdict })

    Add-Line ""
    Add-Line "## $Name"
    Add-Line ""
    Add-Line "_${Why}_"
    Add-Line ""
    Add-Line "**$verdict** (exit $code)$(if ($meaning) { " — $meaning" })"
    Add-Line ""
    # Capped, because the point of this report is that it can be pasted back:
    # a full test run is tens of thousands of lines and the tail is where the
    # verdict and any failure live.
    $lines = $output.TrimEnd() -split "`r?`n"
    $cap = 60

    Add-Line '```'
    if ($lines.Count -gt $cap) {
        Add-Line "[$($lines.Count - $cap) earlier lines omitted]"
        Add-Line ($lines[-$cap..-1] -join "`n")
    } else {
        Add-Line ($lines -join "`n")
    }
    Add-Line '```'

    Write-Host "    $verdict (exit $code)" -ForegroundColor $(
        switch ($verdict) { 'PASS' { 'Green' } 'EXPECTED' { 'Yellow' } default { 'Red' } })
}

# --- environment ------------------------------------------------------------

Add-Line "# Frost — Windows verification run"
Add-Line ""
Add-Line "Generated by ``verify-windows.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')."
Add-Line ""
Add-Line "| | |"
Add-Line "| --- | --- |"
# Each probed separately and tolerantly: the hardware table is context for
# reading the numbers, never a reason to lose a run that already happened.
function Probe([scriptblock]$block) {
    try { $value = & $block; if ($value) { "$value" } else { 'unknown' } }
    catch { 'unknown' }
}

Add-Line "| Machine | $env:COMPUTERNAME |"
Add-Line "| OS | $(Probe { $os = Get-CimInstance Win32_OperatingSystem; "$($os.Caption) build $($os.BuildNumber)" }) |"
Add-Line "| CPU | $(Probe { (Get-CimInstance Win32_Processor | Select-Object -First 1).Name }) |"
Add-Line "| RAM | $(Probe { "$([math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 1)) GB" }) |"
Add-Line "| GPU | $(Probe { (Get-CimInstance Win32_VideoController | ForEach-Object { "$($_.Name) (driver $($_.DriverVersion))" }) -join '<br>' }) |"
Add-Line "| .NET SDK | $(Probe { dotnet --version }) |"
Add-Line "| Capture length | ${Seconds}s |"

# --- build ------------------------------------------------------------------

Invoke-Step -Name 'Build Engine, Shared and tests' `
    -Why 'The part of the solution that must pass. The Engine''s Windows target framework compiles on the Linux build host too, so this is a re-check rather than a first look — but it is the first time it has been built by a Windows SDK.' `
    -Body { dotnet build (Join-Path $repoRoot 'Frost.Linux.slnf') -c Release --nologo }

Invoke-Step -Name 'Unit tests' `
    -Why '750 tests, all of which already pass on the build host. A failure here means something is genuinely platform-dependent.' `
    -Body { dotnet test (Join-Path $repoRoot 'tests/Frost.Engine.Tests/Frost.Engine.Tests.csproj') -c Release --nologo --no-build }

# Attempted separately and expected to fail today: Frost.Shell has a csproj and
# no source files, because Phase 7's XAML is the work that needs this machine.
# Rolling it into the step above would report a FAIL that means nothing.
Invoke-Step -Name 'Build the WinUI 3 Shell (expected to fail until Phase 7)' `
    -Why 'Frost.Shell has no App.xaml or pages yet, so this should fail with CS5001 (no entry point). What matters is *how* it fails: a missing Windows App SDK workload or a broken csproj is a different message, and worth knowing before the XAML is written.' `
    -Body { dotnet build (Join-Path $repoRoot 'src/Frost.Shell/Frost.Shell.csproj') -c Release --nologo }

$engine = Join-Path $repoRoot 'src/Frost.Engine/bin/Release/net8.0-windows10.0.26100.0/Frost.Engine.exe'

if (-not (Test-Path $engine)) {
    $found = Get-ChildItem -Path (Join-Path $repoRoot 'src/Frost.Engine/bin') -Recurse -Filter 'Frost.Engine.exe' -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($found) { $engine = $found.FullName }
}

if (-not (Test-Path $engine)) {
    Add-Line ""
    Add-Line "## Everything below was skipped"
    Add-Line ""
    Add-Line "``Frost.Engine.exe`` was not produced, so there was nothing to run. Fix the build first."
    $report -join "`n" | Set-Content -Path $OutputPath -Encoding utf8
    Write-Host "`nWrote $OutputPath" -ForegroundColor Yellow
    exit 1
}

Add-Line ""
Add-Line "Engine under test: ``$engine``"

# --- the ordered verification list from HANDOFF.md --------------------------

Invoke-Step -Name 'Capture target discovery' `
    -Why 'Windows.Graphics.Capture finds the monitors and windows it can record. Nothing else can work if this does not.' `
    -Body { & $engine --displays; & $engine --windows }

Invoke-Step -Name 'Hardware encoder enumeration' `
    -Why 'Frost is hardware-encode-only by design and never falls back to software x264. This lists the hardware MFTs present and which one it would pick.' `
    -Body { & $engine --encoders }

Invoke-Step -Name 'End-to-end encode, with GPU engine attribution' `
    -Why 'Records the primary display and writes an MP4, then self-checks from PDH counters that the work landed on the video encode engine rather than the CPU or the 3D engine.' `
    -ExitMeanings @{
        5 = 'no keyframes were produced — the encoder ran but the output is unusable'
        6 = 'encoding was NOT on the GPU video encode engine, which breaks the hardware-only rule'
    } `
    -Body { & $engine --encode-test $Seconds (Join-Path $scratch 'encode-test.mp4') }

Invoke-Step -Name 'Ring buffer to clip, with audio' `
    -Why 'Fills the ring buffer and saves a clip with a WASAPI loopback track. This is the first real exercise of AudioTimeline silence insertion against actual WASAPI packet timing, which unit tests can only approximate.' `
    -Body { & $engine --clip-test $Seconds $scratch }

Invoke-Step -Name 'Ring buffer to clip, with microphone as a second track' `
    -Why 'Same, plus the optional mic track. Needs a microphone present and microphone permission granted.' `
    -Body { & $engine --clip-test $Seconds $scratch --mic }

Invoke-Step -Name 'Performance budget' `
    -Why 'Measures the three budget lines that do not need a game running: Engine idle CPU, idle memory, and CPU while ring-buffering. Exits non-zero if a measured line is over budget.' `
    -Body { & $engine --benchmark $Seconds }

if (-not $SkipSoak) {
    Invoke-Step -Name 'Ten-minute memory soak' `
        -Why 'Long capture with a memory verdict, to catch a slow leak the short tests cannot see.' `
        -ExitMeanings @{ 2 = 'working set drifted over 8MB or steady-state allocation over 4KB/s' } `
        -Body { & $engine --soak 10 }
} else {
    Add-Line ""
    Add-Line "## Ten-minute memory soak"
    Add-Line ""
    Add-Line "Skipped (``-SkipSoak``). Run ``Frost.Engine.exe --soak 10`` before trusting the memory numbers."
}

Invoke-Step -Name 'IPC server' `
    -Why 'The Engine/Shell named pipe against a real Windows named pipe. It is tested on the build host, but there over Unix domain sockets. Started and stopped immediately — this only checks the pipe can be created and accepts a connection.' `
    -Body {
        $proc = Start-Process -FilePath $engine -ArgumentList '--ipc-server' -PassThru -WindowStyle Hidden
        Start-Sleep -Seconds 3
        # Enumerated through .NET rather than Get-ChildItem: the pipe filesystem
        # provider is unreliable under Windows PowerShell 5.1.
        $pipe = [System.IO.Directory]::GetFiles('\\.\pipe\') |
            Where-Object { $_ -like '*rost*' } |
            Select-Object -First 1

        if ($pipe) {
            Write-Output "Pipe created: $pipe"
        } else {
            Write-Output 'No Frost pipe found under \\.\pipe\ — the server did not come up.'
        }

        Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
        $global:LASTEXITCODE = $(if ($pipe) { 0 } else { 1 })
    }

# --- what the script cannot do ----------------------------------------------

Add-Line ""
Add-Line "## Still needs a person"
Add-Line ""
Add-Line "Three things cannot be automated, and they are the acceptance criteria for the"
Add-Line "boxes that remain unchecked."
Add-Line ""
Add-Line "1. **The low-level keyboard hook under a fullscreen-exclusive game.** This is the"
Add-Line "   one claim in the whole build with no test behind it. Start a game in"
Add-Line "   fullscreen-exclusive mode (not borderless) and confirm the clip hotkey fires."
Add-Line "   ``WH_KEYBOARD_LL`` was chosen over ``RegisterHotKey`` precisely for this case."
Add-Line ""
Add-Line "2. **PresentMon, before and after.** Capture a game's frame times with the Engine"
Add-Line "   idle, then ring-buffering, then with the Shell also open. Compare the 95th and"
Add-Line "   99th percentiles, not the averages: a capture tool's cost shows up as"
Add-Line "   occasional long frames, which an average hides. README has the procedure."
Add-Line ""
Add-Line "3. **Mica and animations off while a game has focus.** Leave the Shell open behind"
Add-Line "   a focused game and confirm the backdrop and transitions are not drawing."
Add-Line ""
Add-Line "And Phase 10's MSIX package needs ``msbuild`` with the Windows Application"
Add-Line "Packaging tooling, plus a code-signing certificate to install without developer"
Add-Line "mode — the one genuine purchase in the build."

# --- summary ----------------------------------------------------------------

$summary = [System.Collections.Generic.List[string]]::new()
$summary.Add("")
$summary.Add("## Summary")
$summary.Add("")
$summary.Add("| Step | Result |")
$summary.Add("| --- | --- |")
foreach ($r in $results) { $summary.Add("| $($r.Name) | **$($r.Verdict)** (exit $($r.Code)) |") }

$failed = @($results | Where-Object { $_.Verdict -eq 'FAIL' })
$summary.Add("")
$summary.Add($(if ($failed.Count -eq 0) {
    "Every automated step passed."
} else {
    "$($failed.Count) step(s) failed: $(($failed | ForEach-Object { $_.Name }) -join ', ')."
}))

# Summary goes near the top, under the environment table.
$headerEnd = ($report | Select-String -SimpleMatch '| Capture length' | Select-Object -First 1).LineNumber
$final = @()
$final += $report[0..($headerEnd - 1)]
$final += $summary
$final += $report[$headerEnd..($report.Count - 1)]

$final -join "`n" | Set-Content -Path $OutputPath -Encoding utf8

Remove-Item -Recurse -Force $scratch -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Wrote $OutputPath" -ForegroundColor Green
Write-Host ""
foreach ($r in $results) {
    Write-Host ("  {0,-55} {1}" -f $r.Name, $r.Verdict) -ForegroundColor $(if ($r.Verdict -eq 'PASS') { 'Green' } else { 'Red' })
}

exit $(if ($failed.Count -eq 0) { 0 } else { 1 })
